### ISSUE TITLE
Publication on Google Play/iOS App Store?

### ISSUE THREAD

**Issue by rugk** [mapsme/travelguide#1]
When will you publish the app on Google Play and Apples App Store?

I don't like downloading apk files from a website (hosted in Russia :wink:). Especially not without any verification or at least a HTTPS connection.

**Comment by biodranik** [comment]
Guides are already published. Please check http://www.guidewithme.com/

**Comment by rugk** [comment]
That was the website I am talking about. But when will it be published in Google Play e.g.?

**Comment by biodranik** [comment]
I don’t understand your question. Press any link on this site, and it lead you to version published in Google Play.
Or search in Google Play for Travel Guide With Me.

**Comment by rugk** [comment]
Ah okay, so not all regions are published on Google Play yet.
